[package]
name = "dql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
pest = "2.5.7"
pest_derive = "2.5.7"
serde = "1.0.160"
serde_json = "1.0.96"